version: '3.8'
services:
  #  web:
  #    container_name: leetcode-web
  #    build: .
  #    ports:
  #      - "7777:8000"
  #    working_dir: /var/www/app
  #    command: 'uvicorn main:app --host 0.0.0.0 --port 8000 --reload'
  #    volumes:
  #      - ./:/var/www/app
  #    restart: always
  #    depends_on:
  #      - db
  #      - cache
  cache:
    container_name: leetcode-redis
    image: redis:6.2-alpine
    ports:
      - '6369:6379'
  db:
    container_name: leetcode-postgres
    image: postgres:13.3-alpine
    env_file:
      - ".env"
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
