version: '3.8'
services:
  cache:
    container_name: leetcode-redis
    image: redis:6.2-alpine
    ports:
      - '6369:6379'
  db:
    container_name: leetcode-postgres
    image: postgres:13.3-alpine
    env_file:
      - ".env"
    ports:
      - ${DB_PORT}:5432
    environment:
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_NAME}
